[package]
name = "quantic"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "A game engine written in rust for rust and compiles to wasm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]